### ISSUE TITLE
Crystal 0.7.5 compatibility

### ISSUE THREAD

**Issue by jhass** [ysbaddaden/artanis#1]
One issue is in https://github.com/ysbaddaden/artanis/blob/master/src/dsl.cr#L57, `\\Z` is interpreted literally now, replacing it with `\z` (note the lowercase z) works and fixes most tests, but there are a couple of other failures I couldn't figure out.

**Comment by ysbaddaden** [comment]
Thanks! This is fixed in 9ccd98dc2f3fe4c42b3782c5e168f490a82cc92d and I forgot to push 77dce6adea2ba4c3fd5e87615ca37a6acefa5174 which may be fixing the more cryptic failure. At least tests and the sample server are working for me.

**Comment by jhass** [comment]
Works for me, thank you!
