### ISSUE TITLE
Issue with minitest on build

### ISSUE THREAD

**Issue by puppetpies** [ysbaddaden/artanis#10]
Using latest shards / crystal installation.

[brian@orville artanis]$ shards
Updating https://github.com/ysbaddaden/minitest.cr.git
Using minitest (f2014c2175064e0b41bdfdc4b64f8a69b25da075)
[brian@orville artanis]$ make
crystal test/*_test.cr
Error in ./test/dsl_test.cr:1: while requiring "./test_helper"

require "./test_helper"
^

in ./test/test_helper.cr:1: while requiring "../libs/minitest/autorun"

require "../libs/minitest/autorun"
^

in ./libs/minitest/autorun.cr:1: while requiring "./minitest"

require "./minitest"
^

in ./libs/minitest/minitest.cr:5: while requiring "./minitest/test"

require "./minitest/test"
^

in ./libs/minitest/minitest/test.cr:1: while requiring "./assertions"

require "./assertions"
^

Syntax error in ./libs/minitest/minitest/assertions.cr:7: the syntax for an argument with a default value V and type T is `arg : T = V`

  def initialize(@message = nil : String?, @cause = nil : Exception?, @file = **FILE**, @line = **LINE**)
                                ^

Makefile:3: recipe for target 'test' failed
make: **\* [test] Error 1
[brian@orville artanis]$ crystal --version
Crystal 0.14.2 [e1af3d5](Wed Mar 23 00:03:46 UTC 2016)

**Comment by ysbaddaden** [comment]
Crystal rapidly evolves and breaks some compatiblity. A `crystal deps update` will upgrade to the latest minitest that is compatible.

**Comment by puppetpies** [comment]
I have run crystals deps and updated to the latest minitest

[brian@orville artanis]$ crystal deps
Updating https://github.com/ysbaddaden/minitest.cr.git
Using minitest (f2014c2175064e0b41bdfdc4b64f8a69b25da075)

Any ideas i still get the above error ?
