### ISSUE TITLE
Broken test:  test_flushes_body_to_io

### ISSUE THREAD

**Issue by puppetpies** [ysbaddaden/artanis#11]
def test_flushes_body_to_io
    call("GET", "/custom", io = MemoryIO.new)
    body = io.to_s
    assert_match /LAYOUT: CUSTOM/, body
    assert_match /message: custom/, body
  end
## 

[brian@orville artanis]$ make
crystal test/*_test.cr
................F..

Finished in 00:00:00.0068770, 145.412 runs/s

  1) Failure:
Artanis::RenderTest#test_flushes_body_to_io [test/render_test.cr:44]:
Expected /LAYOUT: CUSTOM/ to match: ""

19 tests, 1 failures, 0 errors, 0 skips
Makefile:6: recipe for target 'test' failed
make: **\* [test] Error 255

**Comment by ysbaddaden** [comment]
I used to flush the body, so the test did receive the body on the IO object, but performance degraded dramatically; I changed to simply write the body, and let HTTP::Server flush the response as it needed, but didn't change the test that still needed a flush, since we don't use HTTP::Server.
