### ISSUE TITLE
Enhancement for filters before execution or after

### ISSUE THREAD

**Issue by ray-delossantos** [ysbaddaden/artanis#12]
Hello @ysbaddaden:

I discovered this dsl today, nice work. Is there any way to integrate chained filters for each macro get, post, etc?

For example a normal pattern will be to have jwt integration in a JSON api for a lot of get and post routes, and if there's a pre filter with a token verification error it should always return 403 (forbidden).

Thanks in advance,
raydf

**Comment by ysbaddaden** [comment]
Yes, using `before` which has the same signature than regular routes. I just allowed to call `halt` in filters, so you may:

``` crystal
class AuthenticationApp < Artanis::Application
  def jwt_token
    request.headers["jwt_token"]
  end

  before do
    halt 401 unless JWT.valid_token?(jwt_token)
  end
end
```

**Comment by ray-delossantos** [comment]
How can i bypass the before route for the not_forbidden route?

``` crystal
class AuthenticationApp < Artanis::Application
  def jwt_token
    request.headers["jwt_token"]
  end

  get "/not_forbidden" do
    #skip_before?
    "OK"
  end

  before do
    halt 401 unless JWT.valid_token?(jwt_token)
  end
end
```

**Comment by ysbaddaden** [comment]
`before` can take a path parameter, just like routes. By default its `*` so it always matches, but it can be restricted. Aside from that, there is no precedence; the before filters are always run before the routes, and routes have no way to skip before filters (they may only skip after filters by halting).

**Comment by ray-delossantos** [comment]
Thanks again, @ysbaddaden.
