### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by puppetpies** [ysbaddaden/artanis#9]
[brian@orville artanis]$ make
crystal test/*_test.cr
Error in ./test/dsl_test.cr:1: while requiring "./test_helper"

require "./test_helper"
^

in ./test/test_helper.cr:3: while requiring "../src/artanis"

require "../src/artanis"
^

in ./src/artanis.cr:1: while requiring "./application"

require "./application"
^

in ./src/application.cr:3: while requiring "http/response": can't find file 'http/response' relative to '/data2/Projects/artanis/src'

require "http/response"
^

Makefile:3: recipe for target 'test' failed
make: **\* [test] Error 1

Any ideas ?

**Comment by puppetpies** [comment]
Fixed by upgrading to lastest Crystal 0.14.2-1 release

**Comment by ysbaddaden** [comment]
I'm closing then :-)
